## Fichier : docker-compose.yml
version: '3.8'

services:
  lilith_front:
    container_name: lilith_front
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "25:25"
    restart: always