# docker-compose.prod.yml
services:
  lilith_front:
    container_name: lilith_front
    image: lilith_front
    restart: always
    networks:
      - interservices

networks:
  interservices:
    external: true