server {
  listen 80;

  # Serve les fichiers statiques du dossier public
  location /public/ {
    root /usr/share/nginx/html;
    try_files $uri =404;
  }

  # Configuration pour l'application React
  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
}
