export enum VoteStatus {
  VOTED = "VOTED",
  HAVE_TO_VOTE = "HAVE_TO_VOTE",
  VOTED_AND_REVEAL = "VOTED_AND_REVEAL",
  NO_VOTED_AND_REVEAL = "NO_VOTED_AND_REVEAL",
  VOTED_AND_NOT_REVEAL = "VOTED_AND_NOT_REVEAL",
  NO_VOTED_AND_NOT_REVEAL = "NO_VOTED_AND_NOT_REVEAL",
}